# Generated by Django 2.2.16 on 2021-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.AddField(
            model_name='post',
            name='pin_to_bio',
            field=models.BooleanField(default=False),
        ),
    ]
