# Generated by Django 2.2.16 on 2021-07-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_message_poster_slideshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='pictures',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='SlideshowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.FileField(upload_to='slideshow/')),
                ('slideshow', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Slideshow')),
            ],
        ),
    ]
