# Generated by Django 2.2.16 on 2021-07-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210719_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='image',
            field=models.FileField(upload_to='slideshow/'),
        ),
        migrations.DeleteModel(
            name='SlideshowImage',
        ),
    ]
