# Generated by Django 2.2.16 on 2021-07-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210720_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='title',
        ),
    ]
