# Generated by Django 2.2.16 on 2021-08-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_slideshow_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poster',
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
