# Generated by Django 2.2.16 on 2021-05-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='pin',
            field=models.CharField(max_length=200),
        ),
    ]
