# Generated by Django 2.2.16 on 2021-05-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210504_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
