# Generated by Django 2.2.16 on 2021-05-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210504_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='request_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='store.ProductRequest'),
        ),
    ]
