# Generated by Django 2.2.16 on 2021-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_yarn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='ending_date',
        ),
        migrations.AddField(
            model_name='yarn',
            name='color_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
