# Generated by Django 2.2.16 on 2021-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210806_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='material',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
